cat("\n========== ADPD_cortex_Maxquant ==========\n")
load("C:/Users/tranh/OneDrive/Statistics/cliomicplot/inst/extdata/ADPD_cortex_Maxquant.RData")
cat("data_long cols:", colnames(data_long), "\n")
cat("data_long dim:", dim(data_long), "\n")
cat("Unique groups:", unique(data_long$group), "\n")
print(head(data_long, 3))
cat("results_long cols:", colnames(results_long), "\n")
cat("results_long dim:", dim(results_long), "\n")
cat("Unique tests:", unique(results_long$test), "\n")
nc = ncol(results_long)
print(head(results_long[, c("UniqueID","logFC","P.Value","Adj.P.Value","test")], 5))
cat("\nGene.Name present:", "Gene.Name" %in% colnames(results_long), "\n")
if("Gene.Name" %in% colnames(results_long)) {
  cat("Top genes:\n")
  print(head(results_long[order(results_long$Adj.P.Value), c("UniqueID","Gene.Name","logFC","P.Value","Adj.P.Value")], 10))
}

cat("\n========== AgingHFCD_Metabolomics ==========\n")
rm(list = setdiff(ls(), lsf.str()))
load("C:/Users/tranh/OneDrive/Statistics/cliomicplot/inst/extdata/AgingHFCD_Metabolomics.RData")
cat("data_long cols:", colnames(data_long), "\n")
cat("data_long dim:", dim(data_long), "\n")
cat("Unique groups:", unique(data_long$group), "\n")
print(head(data_long, 3))
cat("results_long cols:", colnames(results_long), "\n")
cat("results_long dim:", dim(results_long), "\n")
cat("Unique tests:", unique(results_long$test), "\n")
print(head(results_long[, 1:min(8,ncol(results_long))], 5))
cat("\nMetaData cols:", colnames(MetaData), "\n")
print(head(MetaData, 3))
